# Generated by Django 2.2.7 on 2019-11-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20191130_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
